### ISSUE TITLE
Button text outside of button

### ISSUE THREAD

**Issue by CaptainM** [CaptainM/recipe#12]
The output on my screen comes from a large nested loop in my application controller.  Since all the data on my screen goes through the exact same loop, I would expect for it to render the same way.  

Unfortunately, I see that for the FIRST 'view full instructions' button, the text 'view full instructions' is OUTSIDE of the button itself.  The other 9 buttons on the page appear normally.  See screenshot below: 

![screen shot 2015-01-26 at 10 08 00 am](https://cloud.githubusercontent.com/assets/7935944/5901805/434921d8-a543-11e4-92fa-a15397dbab3c.png)

Since this information comes from a loop, I don't know why it would work for some elements and not others.  Below is my code for the button itself.  

``` html

<ul class = 'recipe-list'>
    {{#each recipes}}
        <li>{{this.recipe.[0]}}</li>
        <li>{{this.recipe.[1]}}</li>
        {{#each recipe}}
            <li>{{this.ingredient}}</li>
            <li>{{this.amount}}</li>
            <li>{{this.instructions}}</li>
        {{/each}}
        <button class='view' data-iframeurl={{this.recipe.[1]}}>View Full Instructions</button>
    {{/each}}
</ul>
```

@harimohanraj89 @htella @DrRobotmck

**Comment by CaptainM** [comment]
Apparently, if a button has a data attribute that is a url that ends in '/', then the button believe that it has closed.  I chopped off any an all trailing '/', so the buttons look great! 

``` ruby
third_party = doc.css("button#source-full-directions")[0]["link"]
          if third_party.include?("http://")
            no_Http = (third_party[5..-1])
            if no_Http[-1, 1] == '/'
              one_recipe.push(no_Http.chop)
            else
              one_recipe.push(no_Http)
            end
          else
            one_recipe.push('//www.yummly.com' + third_party)
          end
```

**Comment by DrRobotmck** [comment]
:+1:
