### ISSUE TITLE
Extra Blank Spaces without Cause

### ISSUE THREAD

**Issue by CaptainM** [CaptainM/recipe#13]
@harimohanraj89 @htella @DrRobotmck 

For every recipe search, directly after the URL and before the first ingredient, there is consistiently a gap consisting of roughly 6 li elements.  I am unaware of how these blank spaces are appearing, as I cannot account for them in my loop. Below is a screen shot of this blank space (cue taylor swift). 
![screen shot 2015-01-26 at 10 10 59 am](https://cloud.githubusercontent.com/assets/7935944/5901892/f13f8322-a543-11e4-8dfd-202946b3f2ea.png)

I went into my rails console, to see what I was looping over to ensure that there were not a bunch of blank elements. As I suspected, my data appears exactly as I would have expected.  

![screen shot 2015-01-26 at 10 17 58 am](https://cloud.githubusercontent.com/assets/7935944/5901988/abee18dc-a544-11e4-8b0a-570b9c15b109.png)

To try and test out what might be going on, I push a bunch more information into my data (see if you can find it. HINT: it's ridiculous.  

![screen shot 2015-01-26 at 10 21 31 am](https://cloud.githubusercontent.com/assets/7935944/5902094/b0bb1062-a545-11e4-83c3-2c6541acaa51.png)

So, what happens when I add a bunch more stuff into my array? It adds a TON more spaces.  I know that there's a lesson here, but I'm not sure what it is. 

![screen shot 2015-01-26 at 10 28 07 am](https://cloud.githubusercontent.com/assets/7935944/5902121/0fb3c1e0-a546-11e4-9c1e-9385a3412aa7.png)

And look! The 'view full instructions' is INSIDE the button now. Le sigh...

**Comment by harimohanraj89** [comment]
Closing after our conversation.
