### ISSUE TITLE
Scraping

### ISSUE THREAD

**Issue by CaptainM** [CaptainM/recipe#5]
I'm trying to scrape recipes using Nokogiri.  The trouble is, the name of the ingredient (ex. steak) and the amount of the ingredient (ex. 1.5 pounds) are in different divs in the html.  When I parse into the html using nokogiri, I end up with a hash that separates these two values: 

```
    doc = Nokogiri::HTML(HTTParty.get('http://www.yummly.com/recipe/Beef-with-Peppers-The-     Pioneer-Woman-Cooks-_-Ree-Drummond-41172'))

recipe = {}
    test = doc.css('div#content').map do |element|
        # recipe[:calories] = element.css('ul.recipe-data li[2] span.bd').text
        # recipe[:minutes] = element.css('ul.recipe-data li[3] span.bd').text
        recipe[:amount] = element.css('ul li.ingredient span.amount').text
        recipe[:name] = element.css('ul li.ingredient strong.name').text
    end
```

Therefore, when I try to join these two values again, I have great difficulty because each instruction is a different set of words long, and Nokogiri transforms everything into strings when I call 'text'.  I think that a nested loop would work well, but I can't figure out how to do that in Nokogiri.   I think I need some advice on what to do next, as I've spent far too much time on this. 

```
    puts array_of_amounts = recipe[:amount] #.split(',')
    #array_of_ingredients = recipe.values
    puts array_of_ingredients = recipe[:name] #.split(',')
    puts array_of_ingredients.class
    puts array_of_amounts.class
    # array_of_amounts.zip(array_of_ingredients).each do |amount, ingredient|
    #   puts amount 
    #   puts ingredient
    # end
```

Thanks!
@harimohanraj89 @htella @DrRobotmck

**Comment by harimohanraj89** [comment]
Can you post an example of what the relevant HTML on the Yummly page looks like?

**Comment by CaptainM** [comment]
![screen shot 2015-01-22 at 1 08 49 pm](https://cloud.githubusercontent.com/assets/7935944/5861510/e4ff7bd0-a237-11e4-9c69-b97cc9bf507f.png)
